[package]
authors = ["manuel_puentes"]
edition = "2018"
name = "hc_zome_go"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_go"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
derive_more = "0"
serde = {version = "1.0", features = ["derive"]}

hdk = "0.0.115"
holo_hash = {version = "0.0.12", features = ["encoding"]}

goban = "0.17.0"
nat = "0.0.0"

<<<<<<< HEAD:dna/zomes/go/Cargo.toml
hc_mixin_elo = {git = "http://github.com/eyss/elo", rev = "fd5fe6965a91c34cf5b95cec0072c0ae4de848a9"}
hc_mixin_turn_based_game = {git = "http://github.com/eyss/turn-based-game", rev = "5523457dc5cc723e0c4df3e0b009d55e30465e9e"}
=======
hc_mixin_elo = {git = "http://github.com/eyss/elo", rev = "89b6afd2562b16fe79a6eee3372ff971bc2dd14d"}
hc_mixin_turn_based_game = { git = "https://github.com/eyss/turn-based-game", rev = "a58dbb800a00b7c5b3168e895125650c27238b29" }

>>>>>>> prueb:dna/zomes/chess/Cargo.toml
